# Numele aplicatiei
spring.application.name=petcare-backend

# PostgreSQL database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/petcare
spring.datasource.username=postgres
spring.datasource.password=PUNE_PAROLA_TA_DE_LA_BD
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server port
server.port=8081

# Optional: JSON format
spring.jackson.serialization.write-dates-as-timestamps=false

# Debug mode
debug=true

# Modelul folosit de Gemini
gemini.api.key=PUNE_CHEIA_TA_GEMINI

